# Generated by Django 4.1.4 on 2022-12-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=60, verbose_name='Название меню')),
                ('slug', models.SlugField(help_text='Обязательное поле', unique=True, verbose_name='Уникальный слаг меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=60, verbose_name='Название пункта меню')),
                ('path', models.CharField(blank=True, help_text='Пустое для первого уровня меню', max_length=30, verbose_name='Относительный путь к странице')),
                ('menu', models.ForeignKey(help_text='Обязательное поле', on_delete=django.db.models.deletion.CASCADE, to='menu_app.menu', verbose_name='Меню к которому привязан пункт')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='Пустое для первого уровня меню', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.menuitem', verbose_name='Предыдущий уровень меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
